INSERT INTO dls_2.dls_cif_6(DCN_TYPE, C_TYPE, C_CLASS, C_KEY, C_VALUE, EFFECT) VALUES('OW-SN-OP', 'CUS', 'CUS', 'TESTElement0000001', 'OWOP0001', 1); 
INSERT INTO dls_1.dls_cif_6(DCN_TYPE, C_TYPE, C_CLASS, C_KEY, C_VALUE, EFFECT) VALUES('DCN-AC', 'CMM', 'CMM', 'common', 'AC05001', 1); 
INSERT INTO dls_2.dls_cif_6(DCN_TYPE, C_TYPE, C_CLASS, C_KEY, C_VALUE, EFFECT) VALUES('OW-SN-OP', 'CUS', 'CUS', 'TESTElement0000001', 'OWOP0001', 1); 
INSERT INTO dls_3.dls_cif_1(DCN_TYPE, C_TYPE, C_CLASS, C_KEY, C_VALUE, EFFECT) VALUES('OW-SN-OP', 'ACC', 'ACC', 'TESTElement0000001', 'OWOP0001', 1); 
INSERT INTO dls_3.dls_cif_1(DCN_TYPE, C_TYPE, C_CLASS, C_KEY, C_VALUE, EFFECT) VALUES('OW-SN-OP', 'ACC', 'ACC', 'TESTElement0000001', 'OWOP0001', 1); 
COMMIT; 
